version: '3.8'

services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: finpay-postgres-auth
    environment:
      POSTGRES_DB: finpay_auth_db
      POSTGRES_USER: finpay_user
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5434:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  postgres-wallet:
    image: postgres:16-alpine
    container_name: finpay-postgres-wallet
    environment:
      POSTGRES_DB: finpay_wallet_db
      POSTGRES_USER: finpay_user
      POSTGRES_PASSWORD: "0000"
    ports:
      - "5435:5432"
    volumes:
      - wallet_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  wallet_db_data: