server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5433/finpay_wallet_db
    username: finpay_user
    password: finpay_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
